### ISSUE TITLE
Potential text improvements

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#89] opened 2019-05-13 01:00 UTC
20A_04
![image](https://user-images.githubusercontent.com/3904610/57590116-1fa72700-755c-11e9-8e5e-b7f87b78143b.png)
("Wanted" for the red text, for the blackboard, it would be cool to find some flavour / blackboard text from RE2 remake)

30B_00
![ROOM_30B_00](https://user-images.githubusercontent.com/3904610/57590158-6137d200-755c-11e9-9d3e-67043a24e831.png)
("Keep this door closed" <= Since the panel is inside 😄)

The door to the cryo lab/chamber
![image](https://user-images.githubusercontent.com/3904610/57590168-77de2900-755c-11e9-93df-a43576f4367e.png)
("Type P" I guess, the smaller text can be ignored)

**Comment by MoArtis** [comment] 2019-06-14 15:02
The new files are stored in the 1.1 Pack folder.
To test a 1.1 Full pack, Copy the full pack folder and then copy the 1.1 pack one on top of it.

**Comment by Kayael76** [comment] 2019-06-14 20:31
The edits I made work as intended, though I'll let this open just in case new stuff should be done.

**Comment by MoArtis** [comment] 2019-06-15 08:09
It's also ok to open new issues. :) I would argue that it is less depressing. 😂

**Comment by Kayael76** [comment] 2019-06-15 08:10
Ok then, let's close this one and wait for more feedback ^^

**Closed** 2019-06-15 08:11 UTC
Labels: ✨ enhancement, 🎮 to be tested, 👮‍♂️🧟‍♂️ Resident Evil 2
