### ISSUE TITLE
Seam on the right side of the equipped weapon

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#65] opened 2019-04-23 00:53 UTC
![image](https://user-images.githubusercontent.com/3904610/56543633-95932080-65a4-11e9-9a27-e0f366291fb7.png)

Is there a way to avoid that seam on the left side of the equipped weapon?

![image](https://user-images.githubusercontent.com/3904610/56543790-1520ef80-65a5-11e9-8070-c2c1083c7c63.png)

**Comment by Kayael76** [comment] 2019-04-30 19:41
Good eyes ! I'm on TV so I never noticed it. Yes I can fix this, I know why it does that.

**Comment by Kayael76** [comment] 2019-05-03 16:20
I created a 1.1 update folder, I put a fix for this. I you squint enough, you may still see a slight seam, because the bacground of the Equip slot is an empty double-sized slot, and the actual 1 slot weapon is just copy/pasted in the middle of it. Since the gradient I made is way more subtle than the original, it still a bit viewable. I could redo the whole sheet from scratch someday.

![GHAE08-49](https://user-images.githubusercontent.com/48800201/57151024-2bfae980-6dd0-11e9-8c7c-2c66b325b4aa.png)

**Comment by MoArtis** [comment] 2019-05-04 06:25
Seems good enough to me. 👍

**Comment by Kayael76** [comment] 2019-06-14 20:28
Working as intended !

**Closed by Kayael76** 2019-06-14 20:28 UTC
Labels: ✨ enhancement, 🎮 to be tested, 👮‍♂️🧟‍♂️ Resident Evil 2
